//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GottaHaveItAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string EventId { get; set; }
        public string ChannelId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
