//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GottaHaveItAPI.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public string SubscriptionId { get; set; }
        public string ChannelId { get; set; }
        public string ApplicationUserId { get; set; }
    
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Channel Channel { get; set; }
    }
}
